//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SekiroTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SekiroTool.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string AddExperience {
            get {
                return ResourceManager.GetString("AddExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///41 b8 01 00 00 00       mov    r8d,0x1
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string AddSen {
            get {
                return ResourceManager.GetString("AddSen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string ApplySpecialEffect {
            get {
                return ResourceManager.GetString("ApplySpecialEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ff 90 08 01 00 00       call   QWORD PTR [rax+0x108]
        ///81 fb 73 0d 03 00       cmp    ebx,0x30d73
        ///75 11                   jne    1f &lt;exit&gt;
        ///53                      push   rbx
        ///48 8b 18                mov    rbx,QWORD PTR [rax]
        ///81 7b 68 21 ac 08 03    cmp    DWORD PTR [rbx+0x68],0x308ac21
        ///5b                      pop    rbx
        ///75 03                   jne    1f &lt;exit&gt;
        ///48 31 c0                xor    rax,rax
        ///00000000001f &lt;exit&gt;:
        ///e9 00 00 00 00          jmp    24 &lt;exit+0x5&gt;.
        /// </summary>
        internal static string ButterflyNoSummons {
            get {
                return ResourceManager.GetString("ButterflyNoSummons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 48             sub    rsp,0x48
        ///48 8d 4c 24 20          lea    rcx,[rsp+0x20]
        ///ba 8c 0f 00 00          mov    edx,0xf8c
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 8b 4c 24 28          mov    rcx,QWORD PTR [rsp+0x28]
        ///48 83 c4 48             add    rsp,0x48
        ///66 c7 41 2c 33 02       mov    WORD PTR [rcx+0x2c],0x233
        ///c3                      ret.
        /// </summary>
        internal static string ChangeIdolIcon {
            get {
                return ResourceManager.GetString("ChangeIdolIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f3 41 0f 2c c1          cvttss2si eax,xmm9
        ///41 83 7f 28 05          cmp    DWORD PTR [r15+0x28],0x5
        ///74 31                   je     3d &lt;skip_all&gt;
        ///51                      push   rcx
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # 14 &lt;_main+0x14&gt;
        ///48 85 c9                test   rcx,rcx
        ///74 23                   je     3c &lt;skip&gt;
        ///48 8b 89 88 00 00 00    mov    rcx,QWORD PTR [rcx+0x88]
        ///49 3b 8f 90 01 00 00    cmp    rcx,QWORD PTR [r15+0x190]
        ///75 13                   jne    3c &lt;skip&gt;
        ///f3 45 0f  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DamageMultiplier {
            get {
                return ResourceManager.GetString("DamageMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0f 28 b4 24 80 00 00    movaps xmm6,XMMWORD PTR [rsp+0x80]
        ///00 
        ///f3 0f 2c c0             cvttss2si eax,xmm0
        ///80 bc 24 d0 00 00 00    cmp    BYTE PTR [rsp+0xd0],0x0
        ///00 
        ///74 27                   je     3d &lt;skip&gt;
        ///51                      push   rcx
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # 1e &lt;_main+0x1e&gt;
        ///48 85 c9                test   rcx,rcx
        ///74 19                   je     3c &lt;exit&gt;
        ///48 3b b9 88 00 00 00    cmp    rdi,QWORD PTR [rcx+0x88]
        ///75 10                   jne    3c &lt;exit&gt;
        ///f3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DamageMultiplier_Deflect {
            get {
                return ResourceManager.GetString("DamageMultiplier_Deflect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 88 98 42 b7 00 00       mov    BYTE PTR [rax+0xb742],bl
        ///81 78 18 00 75 19 03    cmp    DWORD PTR [rax+0x18],0x3197500
        ///0f 85 15 01 00 00       jne    128 &lt;normal&gt;
        ///57                      push   rdi
        ///48 8d 3d 00 00 00 00    lea    rdi,[rip+0x0]        # 1b &lt;_main+0x1b&gt;
        ///80 3f 04                cmp    BYTE PTR [rdi],0x4
        ///0f 84 03 01 00 00       je     127 &lt;exit&gt;
        ///80 3f 00                cmp    BYTE PTR [rdi],0x0
        ///75 22                   jne    4b &lt;check_stage_1&gt;
        ///fe 05 00 00 00 00       inc    BYTE PTR [rip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DragonActCombo {
            get {
                return ResourceManager.GetString("DragonActCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba ba 00 03 10 00    movabs rdx,0x100300ba
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///48 85 c0                test   rax,rax
        ///74 29                   je     56 &lt;exit&gt;
        ///48 8b 00                mov    rax,QWORD PTR [rax]
        ///48 89 c3                mov    rbx,rax
        ///48 8b 40 58             mov    rax,QWORD PTR [rax+0x58]
        ///48 83  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DragonSkipPhaseOne {
            get {
                return ResourceManager.GetString("DragonSkipPhaseOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 e5                mov    rbp,rsp
        ///48 81 ec 08 06 00 00    sub    rsp,0x608
        ///48 8d 8d e0 fb ff ff    lea    rcx,[rbp-0x420]
        ///ba 00 00 00 00          mov    edx,0x0
        ///e8 00 00 00 00          call   1b &lt;_main+0x1b&gt;
        ///48 8d 8d c8 fb ff ff    lea    rcx,[rbp-0x438]
        ///48 8d 95 98 fa ff ff    lea    rdx,[rbp-0x568]
        ///48 89 51 08             mov    QWORD PTR [rcx+0x8],rdx
        ///4c 8d 85 70 fa ff ff    lea    r8,[rbp-0x590]
        ///4c 89 82 c8 00 00 00    mov    QWORD PTR [rdx+0xc8],r8
        ///49 89 50 20             mov    QWORD PT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExecuteTalkCommand {
            get {
                return ResourceManager.GetString("ExecuteTalkCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 8b 80 f8 1f 00 00    mov    rax,QWORD PTR [rax+0x1ff8]
        ///48 3b 48 18             cmp    rcx,QWORD PTR [rax+0x18]
        ///58                      pop    rax
        ///0f 84 00 00 00 00       je     1a &lt;_main+0x1a&gt;
        ///48 89 5c 24 30          mov    QWORD PTR [rsp+0x30],rbx
        ///e9 00 00 00 00          jmp    24 &lt;_main+0x24&gt;.
        /// </summary>
        internal static string FreezeTargetPosture {
            get {
                return ResourceManager.GetString("FreezeTargetPosture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 89 01                mov    QWORD PTR [rcx],rax
        ///c3                      ret.
        /// </summary>
        internal static string GetChrInsByEntityId {
            get {
                return ResourceManager.GetString("GetChrInsByEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///88 01                   mov    BYTE PTR [rcx],al
        ///c3                      ret.
        /// </summary>
        internal static string GetEvent {
            get {
                return ResourceManager.GetString("GetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 38             sub    rsp,0x38
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # b &lt;_main+0xb&gt;
        ///48 8d 15 00 00 00 00    lea    rdx,[rip+0x0]        # 12 &lt;_main+0x12&gt;
        ///4d 31 c0                xor    r8,r8
        ///4d 31 c9                xor    r9,r9
        ///44 89 44 24 24          mov    DWORD PTR [rsp+0x24],r8d
        ///44 89 44 24 28          mov    DWORD PTR [rsp+0x28],r8d
        ///e8 00 00 00 00          call   27 &lt;_main+0x27&gt;
        ///48 83 c4 38             add    rsp,0x38
        ///c3                      ret.
        /// </summary>
        internal static string GiveItem {
            get {
                return ResourceManager.GetString("GiveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///89 04 24                mov    DWORD PTR [rsp],eax
        ///48 8d 0c 24             lea    rcx,[rsp]
        ///ba 01 00 00 00          mov    edx,0x1
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string GiveSkillsAndPros {
            get {
                return ResourceManager.GetString("GiveSkillsAndPros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000,Spirit Emblem,15
        ///1001,Red Spirit Emblem,5
        ///1100,Regenerative Power,2
        ///1101,Regenerative Power Fragment,100
        ///1110,Temporary Regenerative Power,1
        ///1200,Skill Point,999
        ///2000,Resurrection,1
        ///2100,Bloodsmoke Ninjutsu,1
        ///2110,Puppeteer Ninjutsu,1
        ///2120,Bestowai Ninjutsu,1
        ///2300,Kusabimaru,1
        ///2310,Shinobi Prosthetic,1
        ///2390,Night Eye,1
        ///2400,Mortal Blade,1
        ///2420,Mibu Breathing Technique,1
        ///2450,Anti-air Deathblow Text,1
        ///2460,Dragon Flash,1
        ///2461,Floating Passage Text,1
        ///2462,One Mind,1
        ///2470,Shinobi Medici [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11100000
        ///11110003
        ///12000004
        ///11000000
        ///11000001
        ///11000002
        ///11000003
        ///11000005
        ///11000004
        ///11100000
        ///11100006
        ///11100001
        ///11100002
        ///11100003
        ///11100004
        ///11100005
        ///11100007
        ///11110000
        ///11110001
        ///11110007
        ///11110002
        ///11110003
        ///11110006
        ///11110004
        ///11110005
        ///11120001
        ///11120000
        ///11300000
        ///11300001
        ///11700005
        ///11700004
        ///11700006
        ///11500000
        ///11500001
        ///11500002
        ///11500003
        ///11700007
        ///11700000
        ///11700001
        ///11700002
        ///11700008
        ///11700003
        ///12000000
        ///12000001
        ///12000002
        ///12000003
        ///12000004
        ///12000005
        ///12000006
        ///12500000
        ///12500001
        ///12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IdolEventFlags {
            get {
                return ResourceManager.GetString("IdolEventFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,1001953
        ///1,1101952
        ///2,1111950
        ///3,1121950
        ///6,1301950
        ///7,1501952
        ///9,1701952
        ///11,2001953
        ///12,2501953.
        /// </summary>
        internal static string IdolIdByAreaIndex {
            get {
                return ResourceManager.GetString("IdolIdByAreaIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 184549376,1101950
        ///184614912,1121951
        ///218103808,1111955
        ///335544320,2001950
        ///285212672,1701956
        ///251658240,1501951
        ///419430400,2501950
        ///167772160,1001950.
        /// </summary>
        internal static string IdolsByArea {
            get {
                return ResourceManager.GetString("IdolsByArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81 7b 58 7b 0d 00 00    cmp    DWORD PTR [rbx+0x58],0xd7b
        ///74 15                   je     1e &lt;CheckConfettiFlag&gt;
        ///81 7b 58 71 0d 00 00    cmp    DWORD PTR [rbx+0x58],0xd71
        ///74 1d                   je     2f &lt;CheckGachiinFlag&gt;
        ///f3 0f 5c cf             subss  xmm1,xmm7
        ///0f 2f c1                comiss xmm0,xmm1
        ///e9 00 00 00 00          jmp    1e &lt;CheckConfettiFlag&gt;
        ///000000000000001e &lt;CheckConfettiFlag&gt;:
        ///80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        
        ///75 19                   jne    40 &lt;OriginalI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfiniteConfetti {
            get {
                return ResourceManager.GetString("InfiniteConfetti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 8b 80 88 00 00 00    mov    rax,QWORD PTR [rax+0x88]
        ///48 3b 46 08             cmp    rax,QWORD PTR [rsi+0x8]
        ///58                      pop    rax
        ///0f 84 00 00 00 00       je     1a &lt;_main+0x1a&gt;
        ///4c 89 bc 24 a0 00 00    mov    QWORD PTR [rsp+0xa0],r15
        ///00
        ///e9 00 00 00 00          jmp    27 &lt;_main+0x27&gt;.
        /// </summary>
        internal static string InfinitePoise {
            get {
                return ResourceManager.GetString("InfinitePoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 05 00 00 00 00    mov    QWORD PTR [rip+0x0],rax        # 7 &lt;_main+0x7&gt;
        ///48 8b 80 f8 1f 00 00    mov    rax,QWORD PTR [rax+0x1ff8]
        ///e9 00 00 00 00          jmp    13 &lt;_main+0x13&gt;.
        /// </summary>
        internal static string LockedTarget {
            get {
                return ResourceManager.GetString("LockedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        
        ///48 85 c0                test   rax,rax
        ///74 0c                   je     19 &lt;normal&gt;
        ///80 b8 3d 02 00 00 01    cmp    BYTE PTR [rax+0x23d],0x1
        ///74 03                   je     19 &lt;normal&gt;
        ///0f 57 c0                xorps  xmm0,xmm0
        ///0f 29 83 d0 00 00 00    movaps XMMWORD PTR [rbx+0xd0],xmm0
        ///58                      pop    rax
        ///e9 00 00 00 00          jmp    26 &lt;normal+0xd&gt;.
        /// </summary>
        internal static string NoCameraSpin {
            get {
                return ResourceManager.GetString("NoCameraSpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 8b 80 88 00 00 00    mov    rax,QWORD PTR [rax+0x88]
        ///48 3b 46 08             cmp    rax,QWORD PTR [rsi+0x8]
        ///0f 85 52 01 00 00       jne    16b &lt;normal&gt;
        ///0f 10 b6 80 00 00 00    movups xmm6,XMMWORD PTR [rsi+0x80]
        ///52                      push   rdx
        ///51                      push   rcx
        ///41 50                   push   r8
        ///41 51                   push   r9
        ///53                      push   rbx
        ///4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_CoordsUpdate {
            get {
                return ResourceManager.GetString("NoClip_CoordsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f3 0f 58 87 d0 08 00    addss  xmm0,DWORD PTR [rdi+0x8d0]
        ///00
        ///50                      push   rax
        ///48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 80 88 00 00 00    mov    rax,QWORD PTR [rax+0x88]
        ///48 3b 47 08             cmp    rax,QWORD PTR [rdi+0x8]
        ///75 03                   jne    23 &lt;exit&gt;
        ///0f 57 c0                xorps  xmm0,xmm0
        ///000000000023 &lt;exit&gt;:
        ///58                      pop    rax
        ///e9 00 00 00 00          jmp    29 &lt;exit+0x6&gt;.
        /// </summary>
        internal static string NoClip_InAirTimer {
            get {
                return ResourceManager.GetString("NoClip_InAirTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ff 90 f8 00 00 00       call   QWORD PTR [rax+0xf8]
        ///84 c0                   test   al,al
        ///74 22                   je     2c &lt;exit&gt;
        ///49 83 fc 62             cmp    r12,0x62
        ///74 08                   je     18 &lt;set_down&gt;
        ///49 83 fc 7e             cmp    r12,0x7e
        ///74 0d                   je     23 &lt;set_up&gt;
        ///eb 14                   jmp    2c &lt;exit&gt;
        ///000000000018 &lt;set_down&gt;:
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # 1f &lt;set_down+0x7&gt;
        ///30 c0                   xor    al,al
        ///eb 09               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_Keyboard {
            get {
                return ResourceManager.GetString("NoClip_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 7 &lt;_main+0x7&gt;
        ///0f 84 f3 00 00 00       je     100 &lt;exit&gt;
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # 14 &lt;_main+0x14&gt;
        ///48 8b 89 98 00 00 00    mov    rcx,QWORD PTR [rcx+0x98]
        ///ba 4e 00 00 00          mov    edx,0x4e
        ///48 8b 3d 00 00 00 00    mov    rdi,QWORD PTR [rip+0x0]        # 27 &lt;_main+0x27&gt;
        ///4c 8b bf 88 00 00 00    mov    r15,QWORD PTR [rdi+0x88]
        ///49 8b bf f8 1f 00 00    mov    rdi,QWORD PTR [r15+0x1ff8]
        ///48 8b 7f 68     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_RayCast {
            get {
                return ResourceManager.GetString("NoClip_RayCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 83 f9 0b             cmp    r9d,0xb
        ///74 10                   je     16 &lt;set_down&gt;
        ///41 83 f9 0c             cmp    r9d,0xc
        ///74 12                   je     1e &lt;set_up&gt;
        ///49 89 e3                mov    r11,rsp
        ///53                      push   rbx
        ///56                      push   rsi
        ///e9 00 00 00 00          jmp    16 &lt;set_down&gt;
        ///000000000016 &lt;set_down&gt;:
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # 1d &lt;set_down+0x7&gt;
        ///c3                      ret
        ///00000000001e &lt;set_up&gt;:
        ///c6 05 00 00 00 00 02    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_Triggers {
            get {
                return ResourceManager.GetString("NoClip_Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52                      push   rdx
        ///48 8b 15 00 00 00 00    mov    rdx,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 8b 92 88 00 00 00    mov    rdx,QWORD PTR [rdx+0x88]
        ///48 85 d2                test   rdx,rdx
        ///74 1c                   je     30 &lt;normal&gt;
        ///48 8b 92 f8 1f 00 00    mov    rdx,QWORD PTR [rdx+0x1ff8]
        ///48 85 d2                test   rdx,rdx
        ///74 10                   je     30 &lt;normal&gt;
        ///48 3b 5a 18             cmp    rbx,QWORD PTR [rdx+0x18]
        ///75 0a                   jne    30 &lt;normal&gt;
        ///83 f8 00     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoDeath {
            get {
                return ResourceManager.GetString("NoDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 83 fa 01                cmp    edx,0x1
        ///75 01                   jne    6 &lt;normal&gt;
        ///c3                      ret
        ///000000000006 &lt;normal&gt;:
        ///40 57                      push   rdi
        ///48 83 ec 30             sub    rsp,0x30
        ///e9 00 00 00 00          jmp    10 &lt;normal+0xa&gt;.
        /// </summary>
        internal static string NoMenuMusic {
            get {
                return ResourceManager.GetString("NoMenuMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 83 fa 01                cmp    edx,0x1
        ///75 01                   jne    6 &lt;thisismycode&gt;
        ///c3                      ret
        ///48 89 74 24 10          mov    QWORD PTR [rsp+0x10],rsi
        ///e9 00 00 00 00          jmp    10 &lt;thisismycode+0xa&gt;.
        /// </summary>
        internal static string NoMenuMusicEarlyPatches {
            get {
                return ResourceManager.GetString("NoMenuMusicEarlyPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 48             sub    rsp,0x48
        ///48 8d 0c 24             lea    rcx,[rsp]
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///49 b8 00 00 00 00 00    movabs r8,0x0
        ///00 00 00
        ///49 b9 00 00 00 00 00    movabs r9,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 48             add    rsp,0x48
        ///c3                      ret.
        /// </summary>
        internal static string OpenMenuThreeParams {
            get {
                return ResourceManager.GetString("OpenMenuThreeParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 48             sub    rsp,0x48
        ///48 8d 0c 24             lea    rcx,[rsp]
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///49 b8 00 00 00 00 00    movabs r8,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 48             add    rsp,0x48
        ///c3                      ret.
        /// </summary>
        internal static string OpenMenuTwoParams {
            get {
                return ResourceManager.GetString("OpenMenuTwoParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55                      push   rbp
        ///48 89 e5                mov    rbp,rsp
        ///48 81 ec 00 03 00 00    sub    rsp,0x300
        ///48 8d 8d e0 fd ff ff    lea    rcx,[rbp-0x220]
        ///ba 11 00 00 00          mov    edx,0x11
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///4c 8d ad e0 fd ff ff    lea    r13,[rbp-0x220]
        ///4c 8d b5 c0 fd ff ff    lea    r14,[rbp-0x240]
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///4c 8d 20                lea    r12,[rax]
        ///66 c7 45 fc 0d 10       mov     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenUpgradePrayerBead {
            get {
                return ResourceManager.GetString("OpenUpgradePrayerBead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70000,Loaded Shuriken
        ///70100,Spinning Shuriken
        ///70200,Gouging Top
        ///70300,Phantom Kunai
        ///70400,Sen Throw
        ///70500,Lazulite Shuriken
        ///71000,Shinobi Firecracker
        ///71100,Spring-load Firecracker
        ///71200,Long Spark
        ///71300,Purple Fume Spark
        ///72000,Flame Vent
        ///72100,Spring-load Flame Vent
        ///72200,Okinaga&apos;s Flame Vent
        ///72300,Lazulite Sacred Flame
        ///73000,Loaded Axe
        ///73100,Spring-load Axe
        ///73200,Sparking Axe
        ///73300,Lazulite Axe
        ///74000,Mist Raven
        ///74100,Aged Feather Mist Raven
        ///74200,Great Feather Mist Raven
        ///75000,Sabimaru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prosthetics {
            get {
                return ResourceManager.GetString("Prosthetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 40 08             mov    rax,QWORD PTR [rax+0x8]
        ///48 8b 98 b0 05 00 00    mov    rbx,QWORD PTR [rax+0x5b0]
        ///48 89 d9                mov    rcx,rbx
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 38             sub    rsp,0x38
        ///89 44 24 10             mov    DWORD PTR [rsp+0x10],eax
        ///48 8d 54 24 10          lea    rdx,[rsp+0x10]
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///89 c2                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the HasItem asm script bytes.
        /// </summary>
        internal static string HasItem {
            get {
                return ResourceManager.GetString("HasItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the Emma/Isshin Ashina fight prerequisite flags CSV.
        /// </summary>
        internal static string EmmaIsshinFightFlags {
            get {
                return ResourceManager.GetString("EmmaIsshinFightFlags", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string RemoveSpecialEffect {
            get {
                return ResourceManager.GetString("RemoveSpecialEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///ba 0a 00 00 00          mov    edx,0xa
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///49 b8 00 00 00 00 00    movabs r8,0x0
        ///00 00 00
        ///4d 31 c9                xor    r9,r9
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string SetEvent {
            get {
                return ResourceManager.GetString("SetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200000,Grappling Hook Attack
        ///200100,Mid-air Deflection
        ///200200,Mid-air Prosthetic Tool
        ///200300,Mikiri Counter
        ///200400,Run and Slide
        ///200500,Mid-air Combat Arts
        ///200600,Vault Over
        ///210000,Whirlwind Slash
        ///211000,Shadowrush
        ///301000,Chasing Slice
        ///301100,Fang and Blade
        ///301200,Projected Force
        ///301300,Living Force
        ///310000,Nightjar Slash
        ///310100,Nightjar Slash Reversal
        ///410000,Ichimonji
        ///410100,Ichimonji: Double
        ///411000,Ashina Cross
        ///510000,Praying Strikes
        ///510100,Praying Strikes - Exorcism
        ///511000,Senpou Leapi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///48 85 c0                test   rax,rax
        ///74 22                   je     45 &lt;exit&gt;
        ///48 89 c3                mov    rbx,rax
        ///48 8b 83 f8 1f 00 00    mov    rax,QWORD PTR [rbx+0x1ff8]
        ///48 85 c0                test   rax,rax
        ///74 13                   je     45 &lt;exit&gt;
        ///48 8b 40 18             mov     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkipGeni3 {
            get {
                return ResourceManager.GetString("SkipGeni3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 7 &lt;_main+0x7&gt;
        ///74 4a                   je     53 &lt;exit&gt;
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # 10 &lt;_main+0x10&gt;
        ///48 83 ec 28             sub    rsp,0x28
        ///48 bb 00 00 00 00 00    movabs rbx,0x0
        ///00 00 00
        ///00000000001e &lt;loop&gt;:
        ///80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 25 &lt;loop+0x7&gt;
        ///74 21                   je     48 &lt;end_run&gt;
        ///b9 32 cc 10 00          mov    ecx,0x10cc32
        ///ba 20 4e 00 00          mov     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SnakeCanyonIntroAnimationLoop {
            get {
                return ResourceManager.GetString("SnakeCanyonIntroAnimationLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string StopMusic {
            get {
                return ResourceManager.GetString("StopMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///41 b8 00 00 00 00       mov    r8d,0x0
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string Warp {
            get {
                return ResourceManager.GetString("Warp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0f 10 05 00 00 00 00    movups xmm0,XMMWORD PTR [rip+0x0]        # 7 &lt;_main+0x7&gt;
        ///66 0f 7f 80 D0 0a 00    movdqa XMMWORD PTR [rax+0xaD0],xmm0
        ///00
        ///c3                      ret.
        /// </summary>
        internal static string WarpAngleWrite {
            get {
                return ResourceManager.GetString("WarpAngleWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0f 10 05 00 00 00 00    movups xmm0,XMMWORD PTR [rip+0x0]        # 7 &lt;_main+0x7&gt;
        ///66 0f 7f 80 C0 0a 00    movdqa XMMWORD PTR [rax+0xaC0],xmm0
        ///00
        ///c3                      ret.
        /// </summary>
        internal static string WarpCoordWrite {
            get {
                return ResourceManager.GetString("WarpCoordWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ashina Outskirts,Dilapidated Temple,1101950
        ///Ashina Outskirts,Ashina Outskirts,1101956
        ///Ashina Outskirts,Outskirts Wall - Gate Path,1101951
        ///Ashina Outskirts,Outskirts Wall - Stairway,1101952
        ///Ashina Outskirts,Underbridge Valley,1101953
        ///Ashina Outskirts,Ashina Castle Gate Fortress,1101954
        ///Ashina Outskirts,Ashina Castle Gate,1101955
        ///Ashina Outskirts,Flames of Hatred,1101957
        ///Ashina Castle,Ashina Castle,1111950
        ///Ashina Castle,Upper Tower - Antechamber,1111951
        ///Ashina Castle,Upper Tower - Ashina Dojo,111195 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Warps {
            get {
                return ResourceManager.GetString("Warps", resourceCulture);
            }
        }
    }
}
